# Generated by Django 6.0.4 on 2026-06-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
