# Generated by Django 6.0.4 on 2026-06-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_activity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('day', 'exercise_name')},
        ),
    ]
