# Generated by Django 6.0.4 on 2026-06-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='member_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
