# Generated by Django 6.0.4 on 2026-06-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0007_payment_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Net Banking', 'Net Banking')], default='Cash', max_length=20),
        ),
    ]
