# Generated by Django 6.0.4 on 2026-06-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0010_alter_payment_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expiry_warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
