# Generated by Django 6.0.4 on 2026-07-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0011_payment_expiry_warning_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=20)),
                ('workout_day', models.CharField(default='Chest Day', max_length=50)),
                ('trainer', models.CharField(default='Trainer', max_length=100)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exercises', to='gymapp.member')),
            ],
            options={
                'unique_together': {('member', 'member_day')},
            },
        ),
    ]
