# Generated by Django 6.0.4 on 2026-07-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0013_updatedmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdatedMember',
        ),
        migrations.AddField(
            model_name='member',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
