# Generated by Django 6.0.4 on 2026-07-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0014_delete_updatedmember_member_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='admission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='admission_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='document_image',
            field=models.ImageField(blank=True, null=True, upload_to='members/documents/'),
        ),
        migrations.AddField(
            model_name='member',
            name='document_type',
            field=models.CharField(blank=True, choices=[('AadhaarCard', 'Aadhaar Card'), ('PanCard', 'PAN Card'), ('VoterId', 'Voter ID'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Net_Banking', 'Net_Banking')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('LifeLong', 'LifeLong'), ('1 Year', '1 Year'), ('6 Months', '6 Months'), ('3 Months', '3 Months'), ('1 Month', '1 Month')], max_length=20, null=True),
        ),
    ]
