# Generated by Django 6.0.4 on 2026-07-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0015_member_admission_amount_member_admission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_method',
            field=models.CharField(default='Manual', max_length=30),
        ),
        migrations.AddField(
            model_name='attendance',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
